set1={1,2,3,4,5}
set2={5,6,7,8,1,2}
set_res=set1.union(set2)
print(set_res)
set_res=set1.intersection(set2)
print(set_res)
set_res=set1.difference(set2)
print(set_res)
set_res=set2.difference(set1)
print(set_res)